# Generated by Django 3.0.2 on 2020-01-05 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.EmailValidator], verbose_name='Email Address')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z .'-]+$")], verbose_name='Name')),
            ],
            options={
                'db_table': 'contact',
                'default_permissions': (),
            },
        ),
    ]
