# Generated by Django 3.0.2 on 2020-01-05 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of category.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$')], verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug Name')),
            ],
            options={
                'db_table': 'cook_category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Current Comments')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'comment_cook',
            },
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('is_featured', models.BooleanField(default=False, help_text='Choose if this should be featured.', verbose_name='Featured')),
                ('keyword', models.TextField(help_text='Each keyword is an individual token separated by commas.', verbose_name='Keywords')),
                ('name', models.CharField(help_text='Name of the recipe.', max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z .'-]+$")], verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug Name')),
                ('description', models.TextField(help_text='Write something fancy.', verbose_name='Description')),
                ('directions', models.TextField(help_text='Detailed instructions.', verbose_name='Directions')),
                ('image', models.ImageField(blank=True, help_text='The main image to display.', null=True, upload_to='cook/', verbose_name='Recipe Image')),
                ('ingredients', models.TextField(help_text='List of ingredients you will need for this recipe.', verbose_name='Ingredients')),
                ('serve', models.IntegerField(help_text='How many people can this serve?', verbose_name='Serves')),
                ('time_cook', models.FloatField(help_text='How long does it take to cook?', verbose_name='Cooking Time')),
                ('time_prep', models.FloatField(help_text='How long does it take to prepare before cooking?', verbose_name='Prep Time')),
            ],
            options={
                'db_table': 'cook',
            },
        ),
    ]
