# Generated by Django 3.0.2 on 2020-01-05 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('entry', models.TextField(help_text='Write something fancy.', verbose_name='Entry')),
                ('is_featured', models.BooleanField(default=False, help_text='Choose if this should be featured.', verbose_name='Featured')),
                ('keyword', models.TextField(help_text='Each keyword is an individual token separated by commas.', verbose_name='Keywords')),
                ('name', models.CharField(help_text='Name of the blog.', max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z .'-]+$")], verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug Name')),
                ('video_url', models.URLField(blank=True, help_text='Link to an embeddable video.', null=True, verbose_name='Video URL')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of category.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$')], verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug Name')),
            ],
            options={
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Current Comments')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'comment_blog',
            },
        ),
    ]
