# Generated by Django 3.0.2 on 2020-01-13 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200105_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(help_text='Name of the blog.', max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 .'-]+$")], verbose_name='Name'),
        ),
    ]
