# Generated by Django 3.0.2 on 2020-01-09 21:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of album.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 -]+$')], verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug Name')),
            ],
            options={
                'db_table': 'photo_album',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('is_featured', models.BooleanField(default=False, help_text='Choose if this should be featured.', verbose_name='Featured')),
                ('name', models.CharField(help_text='Name of the photo.', max_length=255, validators=[django.core.validators.RegexValidator("^[a-zA-Z .'-]+$")], verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug Name')),
                ('description', models.TextField(help_text='Write something fancy.', verbose_name='Description')),
                ('image', models.ImageField(help_text='The image to display.', upload_to=photo.models.photo_directory_path, verbose_name='Photo Image')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('album', models.ForeignKey(help_text='Select an album to associate this photo to.', on_delete=django.db.models.deletion.CASCADE, to='photo.Album')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Current Comments')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
            ],
            options={
                'db_table': 'comment_photo',
            },
        ),
    ]
